version: '3.7'

services:
  postgres:
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  prometheus:
    build:
      context: ./prometheus
    ports:
      - "9090:9090"
    restart: always

  grafana:
    build:
      context: ./grafana
    ports:
      - "3000:3000"
    restart: always

  redis:
    image: redis:7.2-bookworm
    ports:
      - "6379:6379"
    restart: always

  airflow-webserver:
    build:
      context: ./airflow
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  airflow-scheduler:
    build:
      context: ./airflow
    command: scheduler
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  dags:
  logs:
  plugins: